### ISSUE TITLE
Query Taxpayer HU+ partner creation error | Standard Odoo error message

### ISSUE THREAD

**Issue by Eilerant** [hungarodo/odoohu-plus#21]
The following tax code cannot be saved for the partner: 30314052

![image](https://github.com/user-attachments/assets/f783e848-5f7c-4484-960c-533d0a565ccd)

Error message:
The VAT number [30314052-2-51] for partner [Rattay Metallschlauch- und Kompensatorentechnik GmbH] does not seem to be valid. 
Note: the expected format is ATU12345675

**Comment by gezzzan** [comment]
@Eilerant this is PRO feature, maybe move issue there
this taxpayer has hungarian VAT number, but HQ country is Austria
when using "Update partner" in the wizard it tries to create a partner with address country austria and Odoo's base vat validation fails for the hungarian VAT format
need to discuss how to handle such cases

**Comment by Eilerant** [comment]
Ticket close - HU+Pro feature
